test

diff --git a/test/sourcing/setup b/test/sourcing/setup
--- a/test/sourcing/setup
+++ b/test/sourcing/setup
@@ -7,8 +7,23 @@ rm -rf ../../v0.10.7
 rm -rf ../../v0.9.7
 rm -rf ../../v0.9.12
 
-\. ../../nvm.sh
-nvm install 0.10.1 || echo >&2 'nvm install 0.10.1 failed'
-nvm install 0.10.3 || echo >&2 'nvm install 0.10.3 failed'
-nvm unalias default || 'removing default alias failed'
-nvm unload || echo >&2 'nvm unload failed'
+if [ -n "${ZSH_VERSION-}" ]; then
+  # these are set by omz: https://github.com/ohmyzsh/ohmyzsh/tree/1ac40cd4456230f09bf0258b173304929d118992/plugins/common-aliases
+  alias -g R='| less -S'
+  alias -g G='| less -S'
+fi
+
+set -e
+
+(
+  \. ../../nvm.sh || echo >&2 'sourcing nvm.sh failed'
+  nvm install 0.10.1 || echo >&2 'nvm install 0.10.1 failed'
+  nvm install 0.10.3 || echo >&2 'nvm install 0.10.3 failed'
+  nvm unalias default || 'removing default alias failed'
+  nvm unload || echo >&2 'nvm unload failed'
+)
+
+if [ -n "${ZSH_VERSION-}" ]; then
+  unalias -g R
+  unalias -g G
+fi
